#!/bin/sh
set -e

lb config noauto \
    --mode debian \
    --distribution bookworm \
    --binary-images iso-hybrid \
    --debian-installer none \
    --memtest none \
    --bootappend-live "boot=live components locales=az_AZ.UTF-8 keyboard-layouts=az,us quiet splash"
    "${@}"
